#!/bin/sh
root=$(git rev-parse --show-toplevel) || exit 1
while read -r local_ref local_oid remote_ref remote_oid; do
  [ "$local_oid" = "0000000000000000000000000000000000000000" ] && continue
  sh "$root/.githooks/_python" --revision "$local_oid" || exit 1
done
