from contextlib import AbstractContextManager
from typing import Any, Protocol


class Database(Protocol):
    def transaction(self) -> AbstractContextManager[Any]: ...


class SeatCache(Protocol):
    def shield(self, event: str, seats: list[str]) -> AbstractContextManager[None]: ...
    def read(self, event: str) -> dict | None: ...


class ReservationStore(Protocol):
    """Each mutation includes atomic ownership checks and durable event creation."""

    def reserve(self, actor, event_id, seat_ids, key) -> dict: ...
    def checkout(self, actor, hold_id, key) -> dict: ...
    def get_order(self, actor, order_id) -> dict: ...
    def get_hold(self, actor, hold_id) -> dict: ...
    def release(self, actor, hold_id) -> dict: ...
    def expire_one(self) -> bool: ...
    def initiate_payment(self, actor, order_id, key, outcome, delay_seconds, duplicates) -> dict: ...
    def callback(self, payload) -> dict: ...
